# Importing basic libraries 

In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [2]:
dataset = pd.read_csv('MODEL2_Complete.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset.head()

Unnamed: 0  policy_tenure  age_of_car  age_of_policyholder  \
0           0       0.515874        0.05             0.644231   
1           1       0.672619        0.02             0.375000   
2           2       0.841110        0.02             0.384615   
3           3       0.900277        0.11             0.432692   
4           4       0.596403        0.11             0.634615   

   population_density  make  segment  airbags  is_esc  is_adjustable_steering  \
0                4990     1        0        2       0                       0   
1               27003     1        0        2       0                       0   
2                4076     1        0        2       0                       0   
3               21622     1        3        2       1                       1   
4               34738     2        0        2       0                       0   

   ...  Disel  Petrol  Brake_Disc  Brake_Drum  Steering_Electric  \
0  ...    0.0     0.0         0.0         1.0                0.0   
1  ...    0.0     0.0         0.0         1.0                0.0   
2  ...    0.0     0.0         0.0         1.0                0.0   
3  ...    0.0     1.0         0.0         1.0                1.0   
4  ...    0.0     1.0         0.0         1.0                1.0   

   Steering_Manual  Steering_Power  Transmission_Automatic  \
0              0.0             1.0                     0.0   
1              0.0             1.0                     0.0   
2              0.0             1.0                     0.0   
3              0.0             0.0                     1.0   
4              0.0             0.0                     1.0   

   Transmission_Manual  is_claim  
0                  1.0         0  
1                  1.0         0  
2                  1.0         0  
3                  0.0         0  
4                  0.0         0  

[5 rows x 49 columns]

In [4]:
print(len(y))
count1 = 0
count2 = 0
for i in y:
    if i==1: count1+=1
    else: count2+=1
print(count1,count2, count1/count2)

58592
3748 54844 0.06833928962147182


# Splitting the dataset

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# Logistic regression
## Importing classifier

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [7]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Testing the model

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10976     0]
 [  743     0]]


0.936598685894701

# Naive Bayes (Gaussian)
## Import Classifier

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Testing the model

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10976     0]
 [  743     0]]


0.936598685894701

# KNN
## Importing classifier

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10952    24]
 [  742     1]]


0.9346360610973633

# Random Forest
## Importing classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 0,class_weight={0:0.5,1:7.8})
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 0.5, 1: 7.8}, random_state=0)

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10974     2]
 [  743     0]]


0.9364280228688454

In [18]:
print(y_train)
count1 = 0
count2 = 0
for i in y_train:
    if i==1: count1+=1
    else: count2+=1
print(count1,count2, count1/count2)

[0 0 0 ... 0 0 0]
3005 43868 0.06850095741770768


In [19]:
class_weight={0:0.5,1:7.1}

In [20]:
len(y_train)

46873