In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [95]:
df = pd.read_csv("Model2.csv")

In [96]:
df.head()

policy_tenure  age_of_car  age_of_policyholder  population_density  M1_enc  \
0       0.515874        0.05             0.644231                4990       1   
1       0.672619        0.02             0.375000               27003       1   
2       0.841110        0.02             0.384615                4076       1   
3       0.900277        0.11             0.432692               21622       0   
4       0.596403        0.11             0.634615               34738       0   

   M10_enc  M11_enc  M2_enc  M3_enc  M4_enc  ...  seg_B2_enc  seg_C1_enc  \
0        0        0       0       0       0  ...           0           0   
1        0        0       0       0       0  ...           0           0   
2        0        0       0       0       0  ...           0           0   
3        0        0       1       0       0  ...           0           1   
4        0        0       0       1       0  ...           0           0   

   seg_C2_enc  seg_utility_enc  make_1_enc  make_2_enc  make_3_enc  \
0           0                0           1           0           0   
1           0                0           1           0           0   
2           0                0           1           0           0   
3           0                0           1           0           0   
4           0                0           0           1           0   

   make_4_enc  make_5_enc  is_claim  
0           0           0         0  
1           0           0         0  
2           0           0         0  
3           0           0         0  
4           0           0         0  

[5 rows x 27 columns]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   policy_tenure        58592 non-null  float64
 1   age_of_car           58592 non-null  float64
 2   age_of_policyholder  58592 non-null  float64
 3   population_density   58592 non-null  int64  
 4   M1_enc               58592 non-null  int64  
 5   M10_enc              58592 non-null  int64  
 6   M11_enc              58592 non-null  int64  
 7   M2_enc               58592 non-null  int64  
 8   M3_enc               58592 non-null  int64  
 9   M4_enc               58592 non-null  int64  
 10  M5_enc               58592 non-null  int64  
 11  M6_enc               58592 non-null  int64  
 12  M7_enc               58592 non-null  int64  
 13  M8_enc               58592 non-null  int64  
 14  M9_enc               58592 non-null  int64  
 15  seg_A_enc            58592 non-null 

In [102]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [103]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   policy_tenure        58592 non-null  float64
 1   age_of_car           58592 non-null  float64
 2   age_of_policyholder  58592 non-null  float64
 3   population_density   58592 non-null  int64  
 4   M1_enc               58592 non-null  int64  
 5   M10_enc              58592 non-null  int64  
 6   M11_enc              58592 non-null  int64  
 7   M2_enc               58592 non-null  int64  
 8   M3_enc               58592 non-null  int64  
 9   M4_enc               58592 non-null  int64  
 10  M5_enc               58592 non-null  int64  
 11  M6_enc               58592 non-null  int64  
 12  M7_enc               58592 non-null  int64  
 13  M8_enc               58592 non-null  int64  
 14  M9_enc               58592 non-null  int64  
 15  seg_A_enc            58592 non-null 

In [104]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [105]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [106]:
x_train.info()

array([[ 1.26375142, -0.69559853, -1.31691159, ..., -0.56492473,
        -0.18536107, -0.19328096],
       [-0.3808375 ,  0.35845266, -1.08208804, ...,  1.77014731,
        -0.18536107, -0.19328096],
       [-0.33287501, -1.22262413,  2.59681425, ..., -0.56492473,
        -0.18536107, -0.19328096],
       ...,
       [-0.22435004,  1.06115346, -0.69071546, ..., -0.56492473,
        -0.18536107, -0.19328096],
       [ 1.20828272,  1.76385425, -0.29934287, ..., -0.56492473,
        -0.18536107, -0.19328096],
       [-0.22152827,  0.70980306,  1.8923436 , ..., -0.56492473,
        -0.18536107, -0.19328096]])

In [30]:
from tensorflow import keras
import tensorflow as tf

In [87]:
from sklearn.utils import class_weight
class_weights = class_weight.compute_class_weight(class_weight='balanced',classes =np.unique(y_train), y=y_train)
class_weights

array([0.53395835, 7.86195907])

In [57]:
ann = tf.keras.models.Sequential()

In [58]:
ann.add(tf.keras.layers.Dense(units=10,activation="relu"))
ann.add(tf.keras.layers.Dense(units=10,activation="relu"))
ann.add(tf.keras.layers.Dense(units=10,activation="relu"))
ann.add(tf.keras.layers.Dense(units=10,activation="relu"))
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [59]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'] )

In [140]:
ann.fit(x_train,y_train,batch_size=32,epochs = 100, class_weight={0:7.8,1:0.5})

Epoch 1/100
1465/1465 [==============================] - 3s 2ms/step - loss: 0.2067 - accuracy: 0.9362
Epoch 2/100
1465/1465 [==============================] - 3s 2ms/step - loss: 0.2016 - accuracy: 0.9362
Epoch 3/100
1465/1465 [==============================] - 3s 2ms/step - loss: 0.2018 - accuracy: 0.9362
Epoch 4/100
1465/1465 [==============================] - 4s 2ms/step - loss: 0.2019 - accuracy: 0.9362
Epoch 5/100
1465/1465 [==============================] - 4s 3ms/step - loss: 0.2021 - accuracy: 0.9362
Epoch 6/100
1465/1465 [==============================] - 4s 3ms/step - loss: 0.2020 - accuracy: 0.9362
Epoch 7/100
1465/1465 [==============================] - 4s 3ms/step - loss: 0.2018 - accuracy: 0.9362
Epoch 8/100
1086/1465 [=====================>........] - ETA: 0s - loss: 0.2017 - accuracy: 0.9361

KeyboardInterrupt: 

In [116]:
base=ann.predict(x_test)

367/367 [==============================] - 1s 1ms/step


In [117]:
base

array([[0.675486  ],
       [0.5455125 ],
       [0.46851116],
       ...,
       [0.44559312],
       [0.4381733 ],
       [0.3970078 ]], dtype=float32)

In [131]:
#threshold=0.5
final_ann=list()
for i in base:
    if i<0.9:
        final_ann.append(0)
    else:
        final_ann.append(1)

In [132]:
accuracy = sum(1 for x,y in zip(final_ann,y_test) if x == y) / float(len(final_ann))

In [133]:
accuracy

0.9354893762266405